name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
        name: build job 1
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: List Repo
            run: ls -ltra

          - name: Executing shell script
            run: |
             chmod +x ascii-script.sh
             ./ascii-script.sh

    test_job_2:
        name: Test job 2
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: List Repo
            run: ls -ltra

          - name: Test File
            run: grep -i "dragon" dragon.txt

    deploy_job_3:
        name: build job 3
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: List Repo
            run: ls -ltra

          - name: read FIle
            run: cat dragon.txt