name: Exploring variable and secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: kevskywalker94
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        name: buid and push on dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$DOCKER_NAME:latest
            
            - name: Docker Login
              env:
                DOCKER_PASSWORD: yesocmr234
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest